# Generated by Django 5.0.3 on 2024-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
